// def gv
//
// pipeline {
//     agent any
//     stages {
//         stage("init") {
//             steps {
//                 script {
//                     gv = load "./module-8/java-maven-app/script.groovy"
//                 }
//             }
//         }
//         stage("build jar") {
//             steps {
//                 script {
// //                     echo "building jar"
//                     gv.buildJar()
//                 }
//             }
//         }
//         stage("build image") {
//             steps {
//                 script {
// //                     echo "building image"
//                     gv.buildImage()
//                 }
//             }
//         }
//         stage("deploy") {
//             steps {
//                 script {
// //                     echo "deploying"
//                     gv.deployApp()
//                 }
//             }
//         }
//     }
// }


pipeline{
    agent any
    tools{
        maven "maven-3.8"
    }

    parameters{
        string(name: 'VERSION', defaultValue:'', description: 'version to deploy on prod')
        choice(name: 'VERSION', choices:['1.1.0', '1.2.0', '1.30'], description: '')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }

    stages {
        stage("build jar"){
            steps{
                script{
                    echo "building the application..."
                    sh 'mvn package package -f ./module-8/java-maven-app/pom.xml'
                }
            }
        }

        stage("build image"){
            steps{
                script{
                    echo "building the docker image..."
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-repo', passwordVariable:'PASS', usernameVariable:'USER')]){
                        sh 'docker build -t stevenchen521/demo-app:jma-2.0 ./module-8/java-maven-app'
                        sh "echo $PASS | docker login -u $USER --password-stdin"
                        sh 'docker push stevenchen521/demo-app:jma-2.0'
                    }
                }
            }
        }

        stage("test"){
            when{
                expression{
                    params.executeTests
                }
            }
            steps{
                echo "testing the application"
            }
        }

        stage("deploy"){
            steps{
                script{
                    echo "deploying the application..."
                    echo "deploying version ${params.VERSION}"
                }
            }
        }


    }

}