pipeline{
    agent any
    tools{
        maven "maven-3.8"
    }
    stages {
        stage("build jar"){
            steps{
                script{
                    echo "building the application..."
                    sh 'mvn package'
                }
            }
        }
        stage("build jar"){
            steps{
                script{
                    echo "building the docker image..."
                    withCredentials([usernamePassword(credentialId: 'docker-hub-repo', passwordVariable:'PASS', usernameVariable:'USER')]){
                        sh 'docker build -t stevenchen521/demo-app:jma-2.0 .'
                        sh "echo $PASS | docker login -u $USER --password-stdin"
                        sh 'docker push stevenchen521/demo-app:jma-2.0'
                    }
                }
            }
        }

        stage("deploy"){
            steps{
                script{
                    echo "deploying the application..."
                }
            }
        }


    }

}